language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "lequal"

jdk:
- openjdk8
- openjdk11

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "target/sonar-icode-cnes-plugin-*.jar"
  skip_cleanup: true
  name: "Sonar i-Code CNES plugin"
  draft: true
  on:
    branch: master
    tags: true
    jdk: 'openjdk11'
